# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 14:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paragraph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(default=1, max_length=400)),
            ],
            options={
                'verbose_name_plural': 'Paragraphs',
                'verbose_name': 'Paragraph',
            },
        ),
    ]
