# -*- coding: utf-8 -*-
# Generated by Django 1.10.1 on 2016-09-06 17:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reader', '0005_auto_20160906_1544'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paragraph',
            name='text',
            field=models.CharField(blank=True, max_length=30000, null=True),
        ),
    ]
